[build]
    image="ChatGPT-Next-Web"
    command = "yarn build"
    publish = ".next"
    functions = "functions"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[context.production.environment]
    NODE_ENV = "production"
