[build]
    command = "yarn build"
    publish = ".next/"


[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer-when-downgrade"

# [[plugins]]
# package = "@netlify/plugin-functions-core"

[context.production.environment]
    NODE_ENV = "production"
